document.writeln("	    <div class=\"bottom\">");
document.writeln("	    	<div class=\"wid\">");
document.writeln("	        	<div class=\"bt_top\">");
document.writeln("	            	<div class=\"bot_menu\">");
document.writeln("	                	<ul>");
document.writeln("	                    	<li>");
document.writeln("	                        	<p>新手引导</p>");
document.writeln("	                            <a href=\"riskTip.html\">风险提示</a>");
document.writeln("	                            <a href=\"comProblem.html\">注册登录</a>");
document.writeln("	                            <a href=\"comProblem.html\">账户安全</a>");
document.writeln("	                            <a href=\"comProblem.html\">下单支付</a>");
document.writeln("	                        </li>");
document.writeln("	                        <li>");
document.writeln("	                        	<p>安全保障</p>");
document.writeln("	                            <a href=\"comProblem.html\">产品安全</a>");
document.writeln("	                            <a href=\"comProblem.html\">产品灵活</a>");
document.writeln("	                            <a href=\"comProblem.html\">账户安全</a>");
document.writeln("	                            <a href=\"comProblem.html\">下单支付</a>");
document.writeln("	                        </li>");
document.writeln("	                        <li>");
document.writeln("	                        	<p>租赁收益</p>");
document.writeln("	                            <a href=\"comProblem.html\">租赁项目</a>");
document.writeln("	                            <a href=\"comProblem.html\">按月付租</a>");
document.writeln("	                            <a href=\"comProblem.html\">计算方式</a>");
document.writeln("	                            <a href=\"comProblem.html\">锁定期限</a>");
document.writeln("	                        </li>");
document.writeln("	                        <li>");
document.writeln("	                        	<p>关于我们</p>");
document.writeln("	                            <a href=\"aboutUs.html\">公司简介</a>");
document.writeln("	                            <a href=\"aboutUs.html\">产品服务</a>");
document.writeln("	                            <a href=\"aboutUs.html\">核心优势</a>");
document.writeln("	                            <a href=\"aboutUs.html\">联系我们</a>");
document.writeln("	                        </li>");
document.writeln("	                        <li>");
document.writeln("	                        	<p>协议及规则</p>");
document.writeln("	                            <a href=\"comProblem.html\">交易服务协议</a>");
document.writeln("	                            <a href=\"comProblem.html\">平台交易规则</a>");
document.writeln("	                            <a href=\"comProblem.html\">信息发布规则</a>");
document.writeln("	                            <a href=\"comProblem.html\">买家委托规则</a>");
document.writeln("	                        </li>");
document.writeln("	");
document.writeln("	                    </ul>");
document.writeln("	                </div>");
document.writeln("	                <div class=\"ico_wei\">");
document.writeln("	                	<img src=\"img/ico3.png\" />");
document.writeln("	                    <img src=\"img/ico4.png\" />");
document.writeln("	                </div>");
document.writeln("	                <div class=\"date\">");
document.writeln("	                    <p>证联金融全国服务热线</p>");
document.writeln("	                    <span>400-888-8888</span>");
document.writeln("	                    <i>人工服务时间：9:00-21:00 </i>");
document.writeln("	                </div>");
document.writeln("	            </div>");
document.writeln("	            <div class=\"link\">");
document.writeln("	            	<p>友情链接：</p>");
document.writeln("	                <span><a href=\"#\">人民网财经</a><a href=\"#\">央视网经济</a></span>");
document.writeln("	                <i>沪ICP备14052990号</i>");
document.writeln("	                <i>北京证联资本管理有限责任公司 @ 2016 All Rights Reserve</i>");
document.writeln("	            </div>");
document.writeln("	        </div>");
document.writeln("	    </div>");
