document.writeln("<div class=\"top\">");
document.writeln("		<div class=\"wid\">");
document.writeln("        	<p>");
document.writeln("            	<a href=\"login.html\">会员登录</a>|");
document.writeln("            	<a href=\"register.html\">免费注册</a>|");
document.writeln("                <a href=\"newBie.html\">新手指南</a>|");
document.writeln("            	<a href=\"comProblem.html\">常见问题</a>");
document.writeln("            </p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"menu\">");
document.writeln("    	<div class=\"wid\">");
document.writeln("        	<img class=\"logo\" src=\"img/logo.png\">");
document.writeln("            <div class=\"menu_list\">");
document.writeln("            	<ul class=\"clearfix\">");
document.writeln("                	<li class=\"acti\"><a href=\"index.html\">首页</a></li>");
document.writeln("                    <li><a href=\"newProduct.html\">优选理财</a></li>");
document.writeln("                    <li><a href=\"newFund.html\">基金</a></li>");
document.writeln("                    <li><a href=\"aboutUs.html\">关于我们</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
